---
root: true
extends: ["eslint:recommended", "google"]
env:
  es6: true
  browser: true

rules:
  indent:
    - warn
    - 4
  prefer-destructuring: off
  brace-style:
    - 2
    - stroustrup
    - allowSingleLine: false
  require-jsdoc: 0
  no-console: 0
  max-len: [2, 140, 4, {"ignoreUrls": true}]

parserOptions:
  sourceType: module
  ecmaVersion: 2019 # for unicode character classes, like \p{N}.

overrides:
  - files: "**/*.test.js"
    env:
      jest: true
      node: true
