name: Semantic release

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run specs
        run: |
          bundle exec rspec
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/commit-analyzer@11
            @semantic-release/release-notes-generator@12
            @semantic-release/changelog@6
            @semantic-release/github@9
            @semantic-release/git@10
            semantic-release-rubygem
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}

