name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Build
        run: scripts/build

      - name: Run specs
        run: bundle exec rspec
